### ISSUE TITLE
TROJAN MALWARE DETECTED

### ISSUE THREAD

**Issue by deiffas** [shemarlindie/presentationtopdf#1]
You can check the virus scan at:
https://www.virustotal.com/gui/file/b7b31208dcc36a2e60442657216914fd9c0b2f5b61a0a0581645d9b24e564e90?nocache=1

**Comment by shemarlindie** [comment]
@deiffas There's no executable in this repo and the code is available for inspection.

Where did you obtain the one that was scanned?
